services:
  postgres:
    image: postgres:17.1-alpine
    container_name: postgres
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - postgres-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - postgres-network
    volumes:
      - redis_data:/data

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
